# Generated by Django 6.0.3 on 2026-03-28 14:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_stripe_hooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='amount_off',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Amount that will be taken off of a subscription', max_digits=8, verbose_name='Amount off'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='max_redemptions',
            field=models.PositiveIntegerField(default=0, help_text='Optional, leave blank for infinite redemptions', verbose_name='Maximum number of redemptions'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='percent_off',
            field=models.PositiveIntegerField(default=0, help_text='Percent that will be taken off of a subscription', verbose_name='Percent off'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='times_redeemed',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Current number of redemptions'),
        ),
        migrations.AlterField(
            model_name='promotioncode',
            name='max_redemptions',
            field=models.PositiveIntegerField(default=0, help_text='Optional, leave blank for infinite redemptions', verbose_name='Maximum number of redemptions'),
        ),
        migrations.AlterField(
            model_name='promotioncode',
            name='times_redeemed',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Current number of redemptions'),
        ),
    ]
