# Generated by Django 6.0.3 on 2026-03-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_stripe_hooks', '0002_alter_coupon_amount_off_alter_coupon_max_redemptions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='amount_off',
            field=models.DecimalField(decimal_places=2, help_text='Amount that will be taken off of a subscription', max_digits=8, verbose_name='Amount off'),
        ),
    ]
