# Generated by Django 6.0.3 on 2026-03-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_stripe_hooks', '0003_alter_coupon_amount_off'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='currency',
            field=models.CharField(choices=[('usd', 'US Dollars')], max_length=3, null=True, verbose_name='Currency'),
        ),
    ]
