# Generated by Django 6.0.3 on 2026-03-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_stripe_hooks', '0004_alter_coupon_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancetransaction',
            name='currency',
            field=models.CharField(choices=[('', 'N/A'), ('usd', 'US Dollars')], max_length=3, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='currency',
            field=models.CharField(choices=[('', 'N/A'), ('usd', 'US Dollars')], max_length=3, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='currency',
            field=models.CharField(choices=[('', 'N/A'), ('usd', 'US Dollars')], default='', max_length=3, verbose_name='Currency'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(choices=[('', 'N/A'), ('usd', 'US Dollars')], max_length=3, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='currency',
            field=models.CharField(choices=[('', 'N/A'), ('usd', 'US Dollars')], max_length=3, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='price',
            name='currency',
            field=models.CharField(choices=[('', 'N/A'), ('usd', 'US Dollars')], max_length=3, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='currency',
            field=models.CharField(choices=[('', 'N/A'), ('usd', 'US Dollars')], max_length=3, verbose_name='Currency'),
        ),
    ]
