# Generated by Django 6.0.3 on 2026-03-28 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_stripe_hooks', '0005_alter_balancetransaction_currency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'ordering': ['-card_exp_year', '-card_exp_month'], 'verbose_name': 'Payment Method', 'verbose_name_plural': 'Payment Methods'},
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='is_default',
        ),
    ]
