# Generated by Django 6.0.3 on 2026-03-28 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_stripe_hooks', '0006_alter_paymentmethod_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentintent',
            name='confirm',
        ),
    ]
