# Generated by Django 6.0.3 on 2026-03-29 03:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_stripe_hooks', '0007_remove_paymentintent_confirm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='current_period_end',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='current_period_start',
        ),
        migrations.AddField(
            model_name='subscriptionitem',
            name='current_period_end',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Current period end'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionitem',
            name='current_period_start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Current period start'),
            preserve_default=False,
        ),
    ]
