# Generated by Django 6.0.3 on 2026-03-29 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_stripe_hooks', '0008_remove_subscription_current_period_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionitem',
            name='deleted',
        ),
    ]
