# Generated by Django 6.0.3 on 2026-03-30 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_stripe_hooks', '0009_remove_subscriptionitem_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charge',
            name='invoice',
        ),
    ]
