# Generated by Django 6.0.3 on 2026-03-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_stripe_hooks', '0010_remove_charge_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='is_attached',
        ),
        migrations.AddField(
            model_name='coupon',
            name='valid',
            field=models.BooleanField(default=True, verbose_name='Valid?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active?'),
            preserve_default=False,
        ),
    ]
